cat <<EOF | oc apply -f -
apiVersion: v1
kind: Namespace
metadata:
  name: default
  labels:
    app: oc-files   
---
apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  name: oc-files
  namespace: default
  labels:
    app: oc-files
spec:
  type: GitHub
  pathname: https://github.com/simonDelordtest/prod-cluster.git
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: prod-cluster
  namespace: default
  labels:
    app: oc-files 
spec:
  clusterConditions:
  - status: "True"
    type: ManagedClusterConditionAvailable
  clusterSelector:
    matchExpressions: []
    matchLabels:
      environment: prod
---
apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: oc-files
  namespace: default
  labels:
    app: oc-files 
spec:
  componentKinds:
  - group: apps.open-cluster-management.io
    kind: Subscription
  descriptor: {}
  selector:
    matchExpressions:
    - key: app
      operator: In
      values:
      - oc-files
---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: oc-files
  namespace: default
  labels:
    app: oc-files
  annotations:
      apps.open-cluster-management.io/github-path:   
spec:
  channel: default/oc-files
  placement:
    placementRef:
      kind: PlacementRule
      name: prod-cluster
      apiGroup: apps.open-cluster-management.io     
EOF
