---
apiVersion: v1
kind: Namespace
metadata:
  name: default
  labels:
    app: prod-repo-app1   
---
apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  name: prod-repo-app1
  namespace: default
  labels:
    app: prod-repo-app1
spec:
  type: GitHub
  pathname: https://github.com/simonDelordtest/prod-repo-app1.git
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: prod-cluster
  namespace: default
  labels:
    app: prod-repo-app1 
spec:
  clusterConditions:
  - status: "True"
    type: ManagedClusterConditionAvailable
  clusterSelector:
    matchExpressions: []
    matchLabels:
      environment: prod
---
apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: prod-repo-app1
  namespace: default
  labels:
    app: prod-repo-app1 
spec:
  componentKinds:
  - group: apps.open-cluster-management.io
    kind: Subscription
  descriptor: {}
  selector:
    matchExpressions:
    - key: app
      operator: In
      values:
      - prod-repo-app1
---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: prod-repo-app1
  namespace: default
  labels:
    app: prod-repo-app1
  annotations:
      apps.open-cluster-management.io/github-path:   
spec:
  channel: default/prod-repo-app1
  placement:
    placementRef:
      kind: PlacementRule
      name: prod-cluster
      apiGroup: apps.open-cluster-management.io     

